name = "SpatiotemporalGPs"
uuid = "73b3b457-46a4-4dae-aece-b1ff83e37843"
authors = ["Devansh Ramgopal Agrawal <devansh@umich.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
